CREATE TABLE ASSETS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL, DESCRIPTION VARCHAR(1000),
WORTH INT NOT NULL, CONFIDENTIALITY BOOLEAN, INTEGRITY BOOLEAN, ACCESSIBILITY BOOLEAN);

CREATE TABLE CATEGORY (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL);

CREATE TABLE GROUPS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70));

CREATE TABLE PROCESSING (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, PROCESS_NAME VARCHAR(70));

CREATE TABLE RISK_STATUS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, STATUS VARCHAR(70) NOT NULL, DESCRIPTION VARCHAR(1000));

CREATE TABLE MANAGER (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL UNIQUE, PASSWORD VARCHAR(20) NOT NULL,
                      COMPANY VARCHAR(70) NOT NULL);

CREATE TABLE RISK (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL, DESCRIPTION VARCHAR(70), LIKELIHOOD INT, LOSS INT,
VALUE INT, PROCESS_ID INT, GROUP_ID INT, CATEGORY_ID INT, STATUS_ID INT, MANAGER_ID INT, ASSET_ID INT, VULNERABILITY_ID INT);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESSING(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_STATUS FOREIGN KEY (STATUS_ID) REFERENCES RISK_STATUS(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_ASSET FOREIGN KEY (ASSET_ID) REFERENCES ASSETS(ID);
ALTER TABLE RISK ADD CONSTRAINT FK_RISK_VUL FOREIGN KEY (VULNERABILITY_ID) REFERENCES VULNERABILITY(ID);

CREATE TABLE THREAT (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL, DESCRIPTION VARCHAR(1000),
ASSET_ID INT);
ALTER TABLE THREAT ADD CONSTRAINT FK_THREAT_ASSET FOREIGN KEY (ASSET_ID) REFERENCES ASSETS(ID);

CREATE TABLE VULNERABILITY (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(70) NOT NULL , DESCRIPTION VARCHAR(1000),
THREAT_ID INT, ASSET_ID INT);
ALTER TABLE VULNERABILITY ADD CONSTRAINT FK_VOLNER_THREAT FOREIGN KEY (THREAT_ID) REFERENCES THREAT(ID);
ALTER TABLE VULNERABILITY ADD CONSTRAINT FK_VOLNER_ASSET FOREIGN KEY (ASSET_ID) REFERENCES ASSETS(ID);


INSERT INTO MANAGER (NAME, PASSWORD, COMPANY) VALUES ('Vlad', 'root', 'EPAM');